### ISSUE TITLE
minify-maven-plugin 1.7.4 does not work with Closure Compiler v20160208 

### ISSUE THREAD

**Issue by andreasrosdal** [samaxes/minify-maven-plugin#119]
When running minify on JavaScript files using minify-maven-plugin 1.7.4, I get this error message:
java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setOutputCharset

I have set the dependency of Closure Compiler to v20160208 in my pom.xml file.

This is the full log:

[INFO] Creating the minified file [webclient.min.js].
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.045 s
[INFO] Finished at: 2016-03-03T20:05:05+00:00
[INFO] Final Memory: 7M/158M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.4:minify (default-minify) on project freeciv-web: java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setOutputCharset(Ljava/lang/String;)V -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.samaxes.maven:minify-maven-plugin:1.7.4:minify (default-minify) on project freeciv-web: java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setOutputCharset(Ljava/lang/String;)V
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setOutputCharset(Ljava/lang/String;)V
        at com.samaxes.maven.minify.plugin.MinifyMojo.execute(MinifyMojo.java:475)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setOutputCharset(Ljava/lang/String;)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:188)
        at com.samaxes.maven.minify.plugin.MinifyMojo.execute(MinifyMojo.java:473)
        ... 22 more
Caused by: java.lang.NoSuchMethodError: com.google.javascript.jscomp.CompilerOptions.setOutputCharset(Ljava/lang/String;)V
        at com.samaxes.maven.minify.plugin.ProcessJSFilesTask.minify(ProcessJSFilesTask.java:114)
        at com.samaxes.maven.minify.plugin.ProcessFilesTask.call(ProcessFilesTask.java:178)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by andreasrosdal** [comment]
Hi again, any updates on if this will be considered? Thanks!

**Comment by samaxes** [comment]
Closed by PR #121
